name: Kiem Tra Frontend
on: [push]

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Lay code ve
        uses: actions/checkout@v3

      - name: Kiem tra file ton tai
        run: |
          if [ -f index.html ]; then
            echo "File index.html co ton tai -> Test OK"
          else
            echo "Loi: Khong tim thay file index.html"
            exit 1
          fi
